module.exports = function (data, process) {

    var branchToProtect = data.parameters.branch || 'master';

    if ( data.payload.ref === ('refs/heads/' + branchToProtect) ) {

        // STEP 1 - branch off.

        var apiUrl = data.payload.repository.git_refs_url.replace('{/sha}', ''),
            newBranchName = branchToProtect + "--super-protected--" + Date.now(),
            options = {
                url: apiUrl,
                headers: {
                    'Content-Type':  'application/json',
                    'User-Agent':    'super-protected-branches',
                    'Authorization': 'token ' + data.access_token
                },
                json: {
                    "ref": "refs/heads/" + newBranchName,
                    "sha": data.payload.after
                }
            };

        request.post(options, function newBranchCreated(err, httpResponse, body) {
            if (err) {
                process.fail('Could not send POST request: ' + err);
            }
            else {
                // STEP 2 - open a Pull Request with new branch.

                apiUrl =
                options.url = data.payload.repository.pulls_url.replace('{/number}', '');
                options.json = {
                    title: data.payload.head_commit.message,
                    body:  'This pull request was automatically generated by the [Super Protected Branches GitHook](http://githooks.io/githooks/GitHooksIO/githook-super-protected-branches) when ' + data.payload.head_commit.author.username + ' tried to push directly to ' + branchToProtect + '.',
                    head:  newBranchName,
                    base:  branchToProtect
                };

                request.post(options, function pullRequestOpened(err, httpResponse, body) {
                    if (err) {
                        process.fail('Could not send POST request: ' + err);
                    }
                    else {
                        process.succeed('Pull request creation was successful. Response: ' + JSON.stringify(body));

                        // STEP 3 - rollback the protected branch to previous state.
                    }
                });

            }
        });

    }
    else {
        process.succeed('the commit was to ' + data.payload.ref + ' and thus was not a problem');
    }
}